using UnityEditor;
using UnityEngine;

namespace NovaForge.Editor
{
    public class NovaForgeAssetProcessor : AssetPostprocessor
    {
        // This runs automatically every time a new .glb is downloaded or updated
        void OnPostprocessModel(GameObject g)
        {
            // Target the terrain mesh generated by the Blender worker
            if (g.name.Contains("Terrain") || g.name.Contains("build_"))
            {
                Renderer[] renderers = g.GetComponentsInChildren<Renderer>();
                foreach (Renderer r in renderers)
                {
                    // Forcing the URP Lit shader which reads Vertex Colors by default
                    Shader vertexShader = Shader.Find("Universal Render Pipeline/Lit");

                    if (vertexShader != null)
                    {
                        // Create a unique material instance to prevent magenta 'Missing Shader' errors
                        Material newMat = new Material(vertexShader);
                        newMat.name = "NovaForge_VertexColor_Material";

                        // Enable GPU instancing to handle high-detail 300x300 grids efficiently
                        newMat.enableInstancing = true;

                        r.sharedMaterial = newMat;
                    }
                    else
                    {
                        Debug.LogWarning("[NovaForge] Could not find 'Universal Render Pipeline/Lit' shader. " +
                                         "Ensure your project is using URP.");
                    }
                }
            }
        }
    }
}
